In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print(a)

In [ ]:
b = np.array([[1,2,3],[4,5,6]]) #2D array (matrix)
print(b)

In [ ]:
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

In [ ]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]]])
print(a)
print(a.shape)

In [6]:
a = np.zeros((2,2,3), dtype=int) #array of zeros
print(a)

In [7]:
b = np.ones((1,2), dtype=int) #array of all ones
print(b)

[[1 1]]


In [8]:
c = np.full((2,3), 7) #constant array
print(c)

[[7 7 7]
 [7 7 7]]


In [9]:
d = np.eye(20, dtype=int) # identity matrix
print(d)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]


In [10]:
e = np.random.random((2,2)) #array filled with random values
print(e)

[[0.65324685 0.34044256]
 [0.39070809 0.93569426]]


In [11]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print(a[1,2])

#use slicinf to pull out the subarray consisting of the first 2 rows and columns 1 and 2; 
#b is the following array shape (2,2)
#a:b a = b -1
b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[[2 3]
 [6 7]]


In [12]:
a = np.array([[1,2], [3,4],[5,6]])
print(a)
bool_idx = (a > 2)
#find the elements of a that are bigger than 2
#this returns a numpy array of Booleans of the same shape as a, where each slot of bool_idx tells whether that element of a is >2


print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [13]:
print(a[bool_idx])

print(a[a > 2])

[3 4 5 6]
[3 4 5 6]
